name: stack-sims slurm

on:
  push:
    branches: 
      - nersc_slurm
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout stack-sims
        uses: actions/checkout@v2
        with:
          ref: nersc_slurm
      - name : Docker prune
        run: sudo docker system prune && df -h 
      - name: do docker build
        run: docker build --no-cache -t lsstdesc/stack-sims:slurm -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: Docker push
        run: docker push lsstdesc/stack-sims:slurm
       
