name: stack-sims v21 latest

on:
  push:
    branches: 
      - v21_0_0

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check Disk Space
        run: df -h && sudo apt-get clean && df -h 
      - name: Docker login
        run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
      - name: checkout stack-sims
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name : Docker prune
        run: sudo docker system prune && df -h 
      - name: do docker build
        run: docker build --no-cache -t lsstdesc/stack-sims:v21_0_0 -f $GITHUB_WORKSPACE/Dockerfile . 
      - name: Docker push
        run: docker push lsstdesc/stack-sims:v21_0_0
       
